#!/bin/bash
# Script to add a user to Linux system
# andre <andre@staff.gramedia.com>

shell=/sbin/nologin
dir=/home/ftp
grp=ftpgrp
if [ $(id -u) -eq 0 ]; then
    read -p "Enter company name : " company
    read -p "Enter username : " username
    read -s -p "Enter password : " password
    egrep "^$username" /etc/passwd >/dev/null
    if [ $? -eq 0 ]; then
        echo "$username exists!"
        exit 1
    else
        pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
         useradd -c "$company" -p $pass -g $grp -s $shell -d $dir/$username -m $                                                                                        username
         [ $? -eq 0 ] && echo "User has been added to system!" && echo "company                                                                                         : $company user: $username, pass: $pass" >> /root/.users || echo "Failed to add                                                                                         a user!"
fi
else
    echo "Only root may add a user to the system"
    exit 2
fi
